python sample_path.py 61 path.txt & 
python sample_path.py 62 path.txt & 
python sample_path.py 63 path.txt & 
python sample_path.py 64 path.txt & 
python sample_path.py 65 path.txt & 
python sample_path.py 66 path.txt & 
python sample_path.py 67 path.txt & 
python sample_path.py 68 path.txt & 
python sample_path.py 69 path.txt & 
python sample_path.py 70 path.txt & 
python sample_path.py 71 path.txt & 
python sample_path.py 72 path.txt & 
python sample_path.py 73 path.txt & 
python sample_path.py 74 path.txt & 
python sample_path.py 75 path.txt & 
python sample_path.py 76 path.txt & 
python sample_path.py 77 path.txt & 
python sample_path.py 78 path.txt & 
python sample_path.py 79 path.txt & 
python sample_path.py 80 path.txt & 
python sample_path.py 81 path.txt & 
python sample_path.py 82 path.txt & 
python sample_path.py 83 path.txt & 
python sample_path.py 84 path.txt & 
python sample_path.py 85 path.txt & 
python sample_path.py 86 path.txt & 
python sample_path.py 87 path.txt & 
python sample_path.py 88 path.txt & 
python sample_path.py 89 path.txt & 
python sample_path.py 90 path.txt & 
