python sample_path.py 1 path.txt & 
python sample_path.py 2 path.txt & 
python sample_path.py 3 path.txt & 
python sample_path.py 4 path.txt & 
python sample_path.py 5 path.txt & 
python sample_path.py 6 path.txt & 
python sample_path.py 7 path.txt & 
python sample_path.py 8 path.txt & 
python sample_path.py 9 path.txt &  
python sample_path.py 10 path.txt & 
python sample_path.py 11 path.txt & 
python sample_path.py 12 path.txt & 
python sample_path.py 13 path.txt & 
python sample_path.py 14 path.txt & 
python sample_path.py 15 path.txt & 
python sample_path.py 16 path.txt & 
python sample_path.py 17 path.txt & 
python sample_path.py 18 path.txt & 
python sample_path.py 19 path.txt & 
python sample_path.py 20 path.txt & 
python sample_path.py 21 path.txt & 
python sample_path.py 22 path.txt &  
python sample_path.py 23 path.txt & 
python sample_path.py 24 path.txt & 
python sample_path.py 25 path.txt & 
python sample_path.py 26 path.txt & 
python sample_path.py 27 path.txt & 
python sample_path.py 28 path.txt & 
python sample_path.py 29 path.txt & 
python sample_path.py 30 path.txt & 
